{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.devportal.kmp",
    "module": "api",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "api-metadata-0.1.0.jar",
          "url": "api-0.1.0.jar",
          "size": 3033,
          "sha512": "67abc5b40777ede5dd19d1ea1aeb3ce4eaf9ff8d432f1de6629017991e30e6a3a35444ed5437d802d73aa107ec843400387cb50178d7d396d3db16b8d7baaa56",
          "sha256": "85e67a5847f1519fe1b3cc613c9e21cbfef880cd34615ee9dbb698c599f2ae2d",
          "sha1": "826470b93907faabd4056b72dc629d664cd9ef82",
          "md5": "773f234d4b7098576c9e6aa3be9c7e57"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "api-kotlin-0.1.0-sources.jar",
          "url": "api-0.1.0-sources.jar",
          "size": 2568,
          "sha512": "94617616ed8f5e2a04577db27cd73f5e599634817ce4bb7c6e3bc49984bf2dc318ee4db79175ee2f9f17790e8c87d2e973dc5a322602fb3d1c901b7d8f0a8354",
          "sha256": "1eb978ca6a241632b16867632eae20ad53b0e9902735581723ba74691e35bd9c",
          "sha1": "55f4de06d470ff9c55e59156c6f9b82fc76a18e3",
          "md5": "ae5ca4b97a9d945067190576e18eadf6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../api-android/0.1.0/api-android-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../api-android/0.1.0/api-android-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../api-android/0.1.0/api-android-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/0.1.0/api-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/0.1.0/api-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/0.1.0/api-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iosarm64/0.1.0/api-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/0.1.0/api-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/0.1.0/api-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/0.1.0/api-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../api-iossimulatorarm64/0.1.0/api-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "api-iossimulatorarm64",
        "version": "0.1.0"
      }
    }
  ]
}
