{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.devportal.kmp",
    "module": "devportal",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mokelab.devportal.kmp",
          "module": "api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.10.0-alpha05"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "devportal-metadata-0.1.0.jar",
          "url": "devportal-0.1.0.jar",
          "size": 2970,
          "sha512": "df7b555bed48e6dd96fe56ccb2eb4ff14d426ff1a8c4de05eaace2a302140eb02090861fbc58a6f1419431fff2a6df18bbb2d7f1504fab18ddf42cbf1160605e",
          "sha256": "cb7141ae6b4ce1a71ce2393befcce4859ac567915b4e58352c1895f63d62506b",
          "sha1": "8e7a8c3ceea0b8af188fb38fd42e5a647805e5ed",
          "md5": "c97f2714364a56dabba3a0d586e86262"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "devportal-kotlin-0.1.0-sources.jar",
          "url": "devportal-0.1.0-sources.jar",
          "size": 3153,
          "sha512": "4ece67ef5167d1111ac850311547e49c1795836adf68c7510884f80957e095dde07aa52b46fbbe87e1333a3edc8f00b77c3cbdcd6b0b73eab9d410eadd980f48",
          "sha256": "fdf609d1261374035527b09b0b408a85f08a1f5283ee682ccfe1bf3cdf140c09",
          "sha1": "29804ee70ac37bfde6768ae7e4bfd9fcdada934b",
          "md5": "7f314cf0b294aa607c695b051dafa58e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../devportal-android/0.1.0/devportal-android-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../devportal-android/0.1.0/devportal-android-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../devportal-android/0.1.0/devportal-android-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iosarm64/0.1.0/devportal-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iosarm64/0.1.0/devportal-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iosarm64/0.1.0/devportal-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iosarm64/0.1.0/devportal-iosarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iossimulatorarm64/0.1.0/devportal-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iossimulatorarm64/0.1.0/devportal-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iossimulatorarm64/0.1.0/devportal-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../devportal-iossimulatorarm64/0.1.0/devportal-iossimulatorarm64-0.1.0.module",
        "group": "com.mokelab.devportal.kmp",
        "module": "devportal-iossimulatorarm64",
        "version": "0.1.0"
      }
    }
  ]
}
